[server]
headless = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#ffffff"
font = "sans serif"

[general]
# Ana başlatma dosyasını belirtiyoruz:
mainPage = "00_Ana_Sayfa.py"
